apiVersion: v1
kind: Service
metadata:
  name: kanban-service
  namespace: kanban-prod
spec:
  type: NodePort
  selector:
    app: kanban-board
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30080